# Generated by Django 3.2 on 2023-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_COMPANY',
            fields=[
                ('cpnyid', models.CharField(db_column='cpnyid', max_length=10, primary_key=True, serialize=False, verbose_name='公司別')),
                ('cocname', models.CharField(db_column='cocname', max_length=255, verbose_name='公司中文名稱')),
                ('coename', models.CharField(blank=True, db_column='coename', max_length=255, null=True, verbose_name='公司英文名稱')),
                ('coscname', models.CharField(blank=True, db_column='coscname', max_length=255, null=True, verbose_name='公司中文簡稱')),
                ('cosename', models.CharField(blank=True, db_column='cosename', max_length=255, null=True, verbose_name='公司英文簡稱')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now_add=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now_add=True, db_column='mtime', verbose_name='異動時間')),
            ],
            options={
                'db_table': 'CRM_COMPANY',
            },
        ),
    ]
