# Generated by Django 3.2 on 2023-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_company',
            name='mdate',
            field=models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期'),
        ),
        migrations.AlterField(
            model_name='crm_company',
            name='mtime',
            field=models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間'),
        ),
    ]
