# Generated by Django 3.2 on 2023-05-03 03:20

import basic_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0002_auto_20230420_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHOPGROUP',
            fields=[
                ('shopgroup_id', models.CharField(db_column='shopgroup_id', max_length=10, primary_key=True, serialize=False, verbose_name='群組編號')),
                ('shopgroup_name', models.CharField(db_column='shopgroup_name', max_length=50, unique=True, verbose_name='群組名稱')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
            ],
            options={
                'db_table': 'SHOPGROUP',
            },
            bases=(models.Model, basic_data.models.CrmQueryData),
        ),
    ]
