# Generated by Django 3.2 on 2023-05-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0003_shopgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('post_id', models.CharField(db_column='post_id', max_length=10, primary_key=True, serialize=False, verbose_name='地區代號')),
                ('post_name', models.CharField(db_column='post_name', max_length=60, verbose_name='地區名稱')),
                ('postal', models.CharField(db_column='postal', max_length=10, verbose_name='郵遞區號')),
                ('muser', models.CharField(db_column='muser', default='admin', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.CharField(db_column='county_id', max_length=10, primary_key=True, serialize=False, verbose_name='縣市代號')),
                ('county_name', models.CharField(db_column='county_name', max_length=60, unique=True, verbose_name='縣市名稱')),
                ('muser', models.CharField(db_column='muser', default='admin', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
            ],
            options={
                'db_table': 'County',
            },
        ),
        migrations.CreateModel(
            name='SHOP',
            fields=[
                ('shop_id', models.CharField(db_column='shop_id', max_length=10, primary_key=True, serialize=False, verbose_name='分店編號')),
                ('shop_name', models.CharField(db_column='shop_name', max_length=30, unique=True, verbose_name='分店名稱')),
                ('shop_scname', models.CharField(db_column='shop_scname', max_length=10, null=True, verbose_name='分店簡稱')),
                ('shop_kind', models.CharField(choices=[('0', '總店'), ('1', '直營店'), ('2', '加盟店')], db_column='shop_kind', max_length=10, null=True, verbose_name='分店類型')),
                ('shop_chief', models.CharField(db_column='shop_chief', max_length=50, null=True, verbose_name='分店店長')),
                ('shop_disable', models.CharField(choices=[('0', '停業'), ('1', '營業中')], db_column='shop_disable', default='1', max_length=1, null=True, verbose_name='營業狀態')),
                ('shop_disable_date', models.DateField(db_column='shop_disable_date', null=True, verbose_name='停業日期')),
                ('shop_note', models.CharField(db_column='shop_note', max_length=50, null=True, verbose_name='分店說明')),
                ('fax', models.CharField(db_column='fax', max_length=30, null=True, verbose_name='傳真號碼')),
                ('telno', models.CharField(db_column='telno', max_length=20, null=True, verbose_name='電話號碼')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('county_id', models.ForeignKey(db_column='county_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.county', verbose_name='所在縣市')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('post_id', models.ForeignKey(db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.area', verbose_name='所在地區')),
                ('shopgroup_id', models.ForeignKey(db_column='shopgroup_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.shopgroup', verbose_name='分店群組')),
            ],
            options={
                'db_table': 'SHOP',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='county_id',
            field=models.ForeignKey(db_column='county_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.county', verbose_name='所屬縣市'),
        ),
    ]
