# Generated by Django 3.2 on 2023-05-04 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0004_auto_20230504_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='county_id',
            field=models.ForeignKey(blank=True, db_column='county_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.county', verbose_name='所在縣市'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='fax',
            field=models.CharField(blank=True, db_column='fax', max_length=30, null=True, verbose_name='傳真號碼'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.area', verbose_name='所在地區'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_chief',
            field=models.CharField(blank=True, db_column='shop_chief', max_length=50, null=True, verbose_name='分店店長'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_disable',
            field=models.CharField(blank=True, choices=[('0', '停業'), ('1', '營業中')], db_column='shop_disable', default='1', max_length=1, null=True, verbose_name='營業狀態'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_disable_date',
            field=models.DateField(blank=True, db_column='shop_disable_date', null=True, verbose_name='停業日期'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_kind',
            field=models.CharField(blank=True, choices=[('0', '總店'), ('1', '直營店'), ('2', '加盟店')], db_column='shop_kind', max_length=10, null=True, verbose_name='分店類型'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_note',
            field=models.CharField(blank=True, db_column='shop_note', max_length=50, null=True, verbose_name='分店說明'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_scname',
            field=models.CharField(blank=True, db_column='shop_scname', max_length=10, null=True, verbose_name='分店簡稱'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopgroup_id',
            field=models.ForeignKey(blank=True, db_column='shopgroup_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.shopgroup', verbose_name='分店群組'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telno',
            field=models.CharField(blank=True, db_column='telno', max_length=20, null=True, verbose_name='電話號碼'),
        ),
    ]
