# Generated by Django 3.2 on 2023-05-13 00:44

import basic_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0006_hruser_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_HRUSER',
            fields=[
                ('empid', models.CharField(db_column='empid', max_length=20, primary_key=True, serialize=False, verbose_name='員工編號')),
                ('cname', models.CharField(db_column='cname', max_length=20, verbose_name='姓名')),
                ('ename', models.CharField(blank=True, db_column='ename', max_length=50, null=True, verbose_name='英文姓名')),
                ('identid', models.CharField(blank=True, db_column='identid', max_length=20, null=True, verbose_name='身份證號')),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True, verbose_name='出生日期')),
                ('pwd', models.CharField(db_column='pwd', max_length=20, verbose_name='密碼')),
                ('telno', models.CharField(blank=True, db_column='telno', max_length=20, null=True, verbose_name='聯絡電話')),
                ('mobilno', models.CharField(blank=True, db_column='mobilno', max_length=20, null=True, verbose_name='行動電話')),
                ('sex', models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], db_column='sex', max_length=2, null=True, verbose_name='性別')),
                ('email', models.CharField(blank=True, db_column='email', max_length=255, null=True, verbose_name='電子信箱')),
                ('indate', models.DateField(blank=True, db_column='indate', null=True, verbose_name='到職日期')),
                ('quitdate', models.DateField(blank=True, db_column='quitdate', null=True, verbose_name='離職日期')),
                ('emp_type', models.CharField(blank=True, choices=[('0', '系統管理者'), ('1', '總部使用者'), ('2', '分店店長'), ('3', '分店員工')], db_column='emp_type', default='3', max_length=2, null=True, verbose_name='員工類型')),
                ('note', models.TextField(blank=True, db_column='note', max_length=255, null=True, verbose_name='備註')),
                ('county_id', models.ForeignKey(blank=True, db_column='county_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.county', verbose_name='所在縣市')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='所屬公司品牌')),
                ('group_id', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.hruser_group', verbose_name='所屬員工群組')),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.area', verbose_name='所在地區')),
                ('shop_id', models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.shop', verbose_name='歸屬分店')),
            ],
            options={
                'db_table': 'CRM_HRUSER',
            },
            bases=(models.Model, basic_data.models.CrmQueryData),
        ),
    ]
