# Generated by Django 3.2 on 2023-05-16 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0008_alter_crm_hruser_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPINFO_GROUP',
            fields=[
                ('vipinfo_group_id', models.CharField(db_column='vipinfo_group_id', max_length=10, primary_key=True, serialize=False, verbose_name='會員群組編號')),
                ('vipinfo_group_name', models.CharField(db_column='vipinfo_group_name', max_length=20, verbose_name='會員群組名稱')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
            ],
            options={
                'db_table': 'VIPINFO_GROUP',
            },
        ),
    ]
