# Generated by Django 3.2 on 2023-05-16 06:46

import basic_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0009_vipinfo_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPINFO',
            fields=[
                ('vip_id', models.CharField(db_column='vip_id', max_length=20, primary_key=True, serialize=False, verbose_name='會員編號')),
                ('vip_name', models.CharField(db_column='vip_name', max_length=50, verbose_name='會員姓名')),
                ('apply_date', models.DateField(db_column='apply_date', verbose_name='申請日期')),
                ('telno', models.CharField(blank=True, db_column='telno', max_length=20, null=True, verbose_name='電話號碼')),
                ('black', models.BooleanField(blank=True, db_column='black', null=True, verbose_name='黑名單')),
                ('sex', models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], db_column='sex', max_length=2, null=True, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True, verbose_name='出生日期')),
                ('edu_lv', models.CharField(blank=True, choices=[('0', '小學畢業'), ('1', '國中畢業'), ('2', '高中畢業'), ('3', '大學畢業'), ('4', '碩士畢業'), ('5', '博士畢業')], db_column='edu_lv', max_length=2, null=True, verbose_name='教育程度')),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True, verbose_name='電子信箱')),
                ('mobilno', models.CharField(blank=True, db_column='mobilno', max_length=20, null=True, verbose_name='行動電話')),
                ('job_cat', models.CharField(blank=True, choices=[('0', '經營/人資類'), ('1', '行政／總務／法務類'), ('2', '財會／金融專業類'), ('3', '經營/人資類'), ('4', '行銷／企劃／專案管理類'), ('5', '經營/人資類'), ('6', '財會／金融專業類'), ('7', '行銷／企劃／專案管理類'), ('8', '客服／門市／業務／貿易類'), ('9', '餐飲／旅遊 ／美容美髮類'), ('10', '資訊軟體系統類'), ('11', '操作／技術／維修類'), ('12', '資材／物流／運輸類'), ('13', '營建／製圖類'), ('14', '營建／製圖類'), ('15', '傳播藝術／設計類'), ('16', '文字／傳媒工作類'), ('17', '醫療／保健服務類'), ('18', '學術／教育／輔導類'), ('19', '研發相關類'), ('20', '生產製造／品管／環衛類'), ('21', '軍警消／保全類')], db_column='job_cat', max_length=3, null=True, verbose_name='職務類別')),
                ('vip_cpny', models.CharField(blank=True, db_column='vip_cpny', max_length=100, null=True, verbose_name='所屬公司名稱')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True, verbose_name='有效日期')),
                ('vip_position', models.CharField(blank=True, db_column='vip_position', max_length=100, null=True, verbose_name='職稱')),
                ('familysize', models.PositiveIntegerField(blank=True, db_column='familysize', null=True, verbose_name='家庭人數')),
                ('ispromote', models.BooleanField(db_column='ispromote', default=True, verbose_name='是否行銷')),
                ('prom_sdate', models.DateField(auto_now_add=True, db_column='prom_sdate', verbose_name='行銷分析開始日')),
                ('vip_FB', models.CharField(blank=True, db_column='vip_FB', max_length=30, null=True, verbose_name='FB帳號')),
                ('vip_IG', models.CharField(blank=True, db_column='vip_IG', max_length=30, null=True, verbose_name='IG帳號')),
                ('vip_LINE', models.CharField(blank=True, db_column='vip_LINE', max_length=30, null=True, verbose_name='LINE帳號')),
                ('note', models.TextField(blank=True, db_column='note', max_length=255, null=True, verbose_name='備註')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('county_id', models.ForeignKey(blank=True, db_column='county_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.county', verbose_name='居住縣市')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.area', verbose_name='居住地區')),
                ('shop_id', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.shop', verbose_name='申請分店')),
                ('vipinfo_group_id', models.ForeignKey(db_column='vipinfo_group_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.vipinfo_group', verbose_name='會員群組')),
            ],
            options={
                'db_table': 'VIPINFO',
            },
            bases=(models.Model, basic_data.models.CrmQueryData),
        ),
    ]
