# Generated by Django 3.2 on 2023-05-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0013_alter_vipinfo_black'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser_group',
            name='cpnyid',
            field=models.ForeignKey(db_column='cpnyid', default='', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopgroup',
            name='cpnyid',
            field=models.ForeignKey(db_column='cpnyid', default='', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vipinfo',
            name='black',
            field=models.BooleanField(db_column='black', default=False, verbose_name='黑名單'),
        ),
    ]
