# Generated by Django 3.2 on 2023-05-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0014_auto_20230523_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_company',
            name='cpnyid',
            field=models.CharField(db_column='cpnyid', max_length=20, primary_key=True, serialize=False, verbose_name='公司別'),
        ),
        migrations.AlterField(
            model_name='hruser_group',
            name='group_id',
            field=models.CharField(db_column='group_id', max_length=20, primary_key=True, serialize=False, verbose_name='員工群組編號'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(db_column='shop_id', max_length=20, primary_key=True, serialize=False, verbose_name='分店編號'),
        ),
        migrations.AlterField(
            model_name='shopgroup',
            name='shopgroup_id',
            field=models.CharField(db_column='shopgroup_id', max_length=20, primary_key=True, serialize=False, verbose_name='分店群組編號'),
        ),
        migrations.AlterField(
            model_name='shopgroup',
            name='shopgroup_name',
            field=models.CharField(db_column='shopgroup_name', max_length=50, unique=True, verbose_name='分店群組名稱'),
        ),
        migrations.AlterField(
            model_name='vipinfo_group',
            name='vipinfo_group_id',
            field=models.CharField(db_column='vipinfo_group_id', max_length=20, primary_key=True, serialize=False, verbose_name='會員群組編號'),
        ),
    ]
