# Generated by Django 3.2 on 2023-05-26 06:53

import basic_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0015_auto_20230526_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('prod_type_id', models.CharField(db_column='prod_type_id', max_length=20, primary_key=True, serialize=False, verbose_name='商品類別編號')),
                ('prod_type_name', models.CharField(db_column='prod_type_name', max_length=40, verbose_name='商品類別名稱')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
            ],
            options={
                'db_table': 'ProductType',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.CharField(db_column='prod_id', max_length=20, primary_key=True, serialize=False, verbose_name='商品編號')),
                ('prod_name', models.CharField(db_column='商品名稱', max_length=40, verbose_name='商品名稱')),
                ('prod_unit', models.CharField(blank=True, db_column='prod_unit', max_length=10, null=True, verbose_name='商品單位')),
                ('price', models.PositiveIntegerField(db_column='price', verbose_name='售價')),
                ('cost_price', models.PositiveIntegerField(blank=True, db_column='cost_price', null=True, verbose_name='成本價')),
                ('return_price', models.PositiveIntegerField(blank=True, db_column='return_price', null=True, verbose_name='退貨成本價')),
                ('fixed_price', models.PositiveIntegerField(blank=True, db_column='fixed_price', null=True, verbose_name='定價')),
                ('emp_price', models.PositiveIntegerField(blank=True, db_column='emp_price', null=True, verbose_name='員工價')),
                ('discount_price', models.PositiveIntegerField(blank=True, db_column='discount_price', null=True, verbose_name='折扣價')),
                ('discount_rate', models.DecimalField(blank=True, db_column='discount_rate', decimal_places=2, max_digits=5, null=True, verbose_name='折扣率')),
                ('origin', models.CharField(blank=True, db_column='origin', max_length=10, null=True, verbose_name='產地')),
                ('barcode', models.CharField(blank=True, db_column='barcode', max_length=50, null=True, verbose_name='條碼')),
                ('note', models.TextField(blank=True, db_column='note', max_length=255, null=True, verbose_name='備註')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('prod_type_id', models.ForeignKey(blank=True, db_column='prod_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_data.producttype', verbose_name='所屬商品類別編號')),
            ],
            options={
                'db_table': 'Product',
            },
            bases=(models.Model, basic_data.models.CrmQueryData),
        ),
    ]
