# Generated by Django 3.2 on 2023-06-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0016_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(db_column='prod_name', max_length=40, verbose_name='商品名稱'),
        ),
    ]
