# Generated by Django 3.2 on 2023-06-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0017_alter_product_prod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_company',
            name='cdate',
            field=models.DateField(db_column='cdate', verbose_name='品牌創立日期'),
        ),
    ]
