# Generated by Django 3.2 on 2023-05-31 06:06

import basic_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_data', '0016_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP_LABEL_GROUP',
            fields=[
                ('label_gid', models.CharField(db_column='label_gid', max_length=20, primary_key=True, serialize=False, verbose_name='標籤群組代號')),
                ('label_gname', models.CharField(db_column='label_gname', max_length=50, unique=True, verbose_name='標籤群組名稱')),
                ('descr', models.TextField(blank=True, db_column='descr', null=True, verbose_name='標籤群組描述')),
                ('color', models.CharField(db_column='color', max_length=8, verbose_name='標籤群組標記顏色')),
                ('xor', models.CharField(choices=[('0', '允許選擇多標籤'), ('1', '僅能選擇單一標籤')], db_column='xor', default='1', max_length=2, verbose_name='貼標時客人是否可以擁有群組內一個以上的標籤')),
                ('label_enable', models.CharField(choices=[('0', '否'), ('1', '是')], db_column='label_enable', default='0', max_length=2, verbose_name='是否停用')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
            ],
            options={
                'db_table': 'VIP_LABEL_GROUP',
            },
            bases=(models.Model, basic_data.models.CrmQueryData),
        ),
    ]
