# Generated by Django 3.2 on 2023-05-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label_data', '0002_formula_paramater_vip_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_label_group',
            name='formula_id',
            field=models.ForeignKey(db_column='formula_id', default='', on_delete=django.db.models.deletion.CASCADE, to='label_data.formula', verbose_name='標籤計算公式'),
            preserve_default=False,
        ),
    ]
