# Generated by Django 3.2 on 2023-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_data', '0004_auto_20230601_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramater',
            name='mdate',
            field=models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期'),
        ),
        migrations.AddField(
            model_name='paramater',
            name='mtime',
            field=models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間'),
        ),
        migrations.AddField(
            model_name='paramater',
            name='muser',
            field=models.CharField(db_column='muser', default='', max_length=20, verbose_name='異動者'),
            preserve_default=False,
        ),
    ]
