# Generated by Django 3.2 on 2023-06-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0017_alter_product_prod_name'),
        ('label_data', '0005_auto_20230605_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales00',
            fields=[
                ('sale00_id', models.CharField(db_column='sale00_id', max_length=30, primary_key=True, serialize=False, verbose_name='銷售單據單號')),
                ('card_no', models.CharField(blank=True, db_column='card_no', max_length=30, null=True, verbose_name='會員卡號')),
                ('sale_status', models.CharField(blank=True, choices=[('1', '存檔'), ('2', '作廢')], db_column='sale_status', default='1', max_length=2, null=True, verbose_name='交易狀態')),
                ('sale_type', models.CharField(blank=True, choices=[('1', '普通'), ('2', '訂貨提領'), ('3', '有換貨')], db_column='sale_type', default='1', max_length=2, null=True, verbose_name='銷售類型')),
                ('goods_type', models.CharField(blank=True, choices=[('1', '銷貨單'), ('2', '銷退單'), ('3', '已被退銷貨單')], db_column='goods_type', default='1', max_length=2, null=True, verbose_name='退貨標誌')),
                ('tot_quan', models.CharField(db_column='tot_quan', max_length=5, verbose_name='總銷售數量')),
                ('tot_sales', models.CharField(db_column='tot_sales', max_length=10, verbose_name='總銷售金額')),
                ('cuser', models.CharField(db_column='cuser', max_length=20, verbose_name='創始人')),
                ('cdate', models.DateField(auto_now_add=True, db_column='cdate', verbose_name='創立日期')),
                ('ctime', models.TimeField(auto_now_add=True, db_column='ctime', verbose_name='創立時間')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('shop_id', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.shop', verbose_name='消費分店')),
                ('vip_id', models.ForeignKey(db_column='vip_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.vipinfo', verbose_name='會員編號')),
            ],
            options={
                'db_table': 'sales00',
                'unique_together': {('cpnyid', 'shop_id', 'sale00_id')},
            },
        ),
        migrations.CreateModel(
            name='Sale01',
            fields=[
                ('sale01_id', models.CharField(db_column='sale01_id', max_length=30, primary_key=True, serialize=False, verbose_name='交易明細序號')),
                ('qty', models.CharField(db_column='qty', max_length=5, verbose_name='購買商品數量')),
                ('price', models.CharField(db_column='price', max_length=5, verbose_name='商品單價')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.product', verbose_name='商品編號')),
                ('sale00_id', models.ForeignKey(db_column='sale00_id', on_delete=django.db.models.deletion.CASCADE, to='label_data.sales00', verbose_name='銷售單據單號')),
                ('shop_id', models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.shop', verbose_name='消費分店')),
            ],
            options={
                'db_table': 'sales01',
                'unique_together': {('sale00_id', 'sale01_id', 'prod_id')},
            },
        ),
    ]
