# Generated by Django 3.2 on 2023-06-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_data', '0017_alter_product_prod_name'),
        ('label_data', '0008_auto_20230610_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP_LABEL_STAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calsdate', models.DateField(blank=True, db_column='calsdate', null=True, verbose_name='計算日起')),
                ('caledate', models.DateField(blank=True, db_column='caledate', null=True, verbose_name='計算日迄')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('label_id', models.ForeignKey(db_column='label_id', on_delete=django.db.models.deletion.CASCADE, to='label_data.vip_label', verbose_name='標籤編號')),
                ('vip_id', models.ForeignKey(db_column='vip_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.vipinfo', verbose_name='會員編號')),
            ],
            options={
                'db_table': 'vip_label_stat',
                'unique_together': {('cpnyid', 'vip_id', 'label_id')},
            },
        ),
        migrations.CreateModel(
            name='VIP_FORMULA_STAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(db_column='result_value', max_length=30, verbose_name='計算結果值')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('formula_id', models.ForeignKey(db_column='formula_id', on_delete=django.db.models.deletion.CASCADE, to='label_data.formula', verbose_name='公式編號')),
                ('vip_id', models.ForeignKey(db_column='vip_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.vipinfo', verbose_name='會員編號')),
            ],
            options={
                'db_table': 'vip_formula_stat',
                'unique_together': {('cpnyid', 'vip_id', 'formula_id')},
            },
        ),
        migrations.CreateModel(
            name='PARAMATER_STAT_COMPANY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_value', models.CharField(db_column='param_value', max_length=30, verbose_name='參數值')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('param_id', models.ForeignKey(db_column='param_id', on_delete=django.db.models.deletion.CASCADE, to='label_data.paramater', verbose_name='參數編號')),
            ],
            options={
                'db_table': 'paramater_stat_company',
                'unique_together': {('cpnyid', 'param_id')},
            },
        ),
        migrations.CreateModel(
            name='PARAMATER_STAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_value', models.CharField(db_column='param_value', max_length=30, verbose_name='參數值')),
                ('muser', models.CharField(db_column='muser', max_length=20, verbose_name='異動者')),
                ('mdate', models.DateField(auto_now=True, db_column='mdate', verbose_name='異動日期')),
                ('mtime', models.TimeField(auto_now=True, db_column='mtime', verbose_name='異動時間')),
                ('cpnyid', models.ForeignKey(db_column='cpnyid', on_delete=django.db.models.deletion.CASCADE, to='basic_data.crm_company', verbose_name='公司品牌')),
                ('param_id', models.ForeignKey(db_column='param_id', on_delete=django.db.models.deletion.CASCADE, to='label_data.paramater', verbose_name='參數編號')),
                ('vip_id', models.ForeignKey(db_column='vip_id', on_delete=django.db.models.deletion.CASCADE, to='basic_data.vipinfo', verbose_name='會員編號')),
            ],
            options={
                'db_table': 'paramater_stat',
                'unique_together': {('cpnyid', 'vip_id', 'param_id')},
            },
        ),
    ]
