# Generated by Django 3.2 on 2023-06-11 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_data', '0010_formula_formula_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale01',
            name='price',
            field=models.IntegerField(db_column='price', verbose_name='商品單價'),
        ),
        migrations.AlterField(
            model_name='sale01',
            name='qty',
            field=models.IntegerField(db_column='qty', verbose_name='購買商品數量'),
        ),
        migrations.AlterField(
            model_name='sales00',
            name='input_date',
            field=models.DateField(db_column='input_date', default=datetime.date(2023, 6, 11), verbose_name='入賬(消費)日期'),
        ),
        migrations.AlterField(
            model_name='sales00',
            name='tot_quan',
            field=models.IntegerField(db_column='tot_quan', verbose_name='總銷售數量'),
        ),
        migrations.AlterField(
            model_name='sales00',
            name='tot_sales',
            field=models.IntegerField(db_column='tot_sales', verbose_name='總銷售金額'),
        ),
    ]
